spring:
  application:
    name: api-gateway
  profiles:
    active: docker
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:edutech_db}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER:edutech_user}
    password: ${DB_PASSWORD:edutech_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8762

# Configuración simplificada de Gateway
gateway:
  routes:
    - id: persona-service
      uri: http://microservicio-persona:8081
      predicates:
        - Path=/api/personas/**
    - id: curso-service
      uri: http://microservicio-curso:8082
      predicates:
        - Path=/api/cursos/**
    - id: ejecucion-service
      uri: http://microservicio-ejecucion:8083
      predicates:
        - Path=/api/ejecuciones/**
    - id: evaluacion-service
      uri: http://microservicio-evaluacion:8084
      predicates:
        - Path=/api/evaluaciones/**
    - id: comunicacion-service
      uri: http://microservicio-comunicacion:8085
      predicates:
        - Path=/api/comunicacion/**

logging:
  level:
    com.edutech: DEBUG
