server:
  port: 8080
  tomcat:
    max-swallow-size: 10485760    
    max-http-form-post-size: 10485760 

spring:
  application:
    name: api_gateway
  mvc:
    problemdetails:
      enabled: true
  cloud:
    gateway:
      mvc:
        # Para el caso de gateway-mvc, usamos routes
        routes:
          - id: microservicio_persona
            uri: http://localhost:8081
            predicates:
              - Path=/api/personas/**

          - id: microservicio_curso
            uri: http://localhost:8082
            predicates:
              - Path=/api/cursos/**
          
          - id: microservicio_ejecucion
            uri: http://localhost:8084
            predicates:
              - Path=/api/ejecuciones/**,/api/inscripciones/**
          
          - id: microservicio_comunicacion
            uri: http://localhost:8085
            predicates:
              - Path=/api/mensajes/**,/api/notificaciones/**
          
          - id: microservicio_evaluacion
            uri: http://localhost:8086
            predicates:
              - Path=/api/evaluaciones/**,/api/preguntas/**,/api/opciones/**,/api/calificaciones/**,/api/respuestas/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
