server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservicio-persona
          uri: lb://microservicio-persona
          predicates:
            - Path=/api/personas/**
        - id: microservicio-curso
          uri: lb://microservicio-curso
          predicates:
            - Path=/api/cursos/**
        - id: microservicio-ejecucion
          uri: lb://microservicio-ejecucion
          predicates:
            - Path=/api/ejecuciones/**
        - id: microservicio-comunicacion
          uri: lb://microservicio-comunicacion
          predicates:
            - Path=/api/comunicaciones/**
        - id: microservicio-evaluacion
          uri: lb://microservicio-evaluacion
          predicates:
            - Path=/api/evaluaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    preferIpAddress: true

# Configuración de Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
