spring:
  application:
    name: microservicio-comunicacion
  profiles:
    active: docker
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:edutech_db}?createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DB_USER:edutech_user}
    password: ${DB_PASSWORD:edutech_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8085

# URL del microservicio persona
microservicio:
  persona:
    url: http://microservicio-persona:8081

logging:
  level:
    com.edutech: DEBUG
