global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api_gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "microservicio_persona"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "microservicio_curso"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "microservicio_ejecucion"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]

  - job_name: "microservicio_comunicacion"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8085"]

  - job_name: "microservicio_evaluacion"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8086"]